language: node_js

node_js:
  - stable

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run test

deploy:
    provider: npm
    email: 675129745@qq.com
    api_key: "$NPM_TOKEN"
    skip_cleanup: true
    on:
        all_branches: true